import kotlin.String

/**
 * Generated by [gradle-kotlin-dsl-libs](https://github.com/jmfayard/gradle-kotlin-dsl-libs)
 *
 * Run again
 *   `$ ./gradlew syncLibs`
 * to update this file */
object Versions {
    /**
     * [espresso-core website](https://developer.android.com/testing) */
    const val espresso_core: String = "3.0.2" // up-to-date

    /**
     * [runner website](https://developer.android.com/testing) */
    const val com_android_support_test_runner: String = "1.0.2" // up-to-date

    /**
     * [appcompat-v7 website](http://developer.android.com/tools/extras/support-library.html) */
    const val appcompat_v7: String = "28.0.0" // up-to-date

    /**
     * [aapt2 website](https://developer.android.com/studio) */
    const val aapt2: String = "3.2.1-4818971" // available milestone: "3.4.0-alpha02-5013011" 

    /**
     * [gradle website](https://developer.android.com/studio) */
    const val com_android_tools_build_gradle: String =
            "3.2.1" // available milestone: "3.4.0-alpha02" 

    /**
     * [lint-gradle website](https://developer.android.com/studio) */
    const val lint_gradle: String = "26.2.1" // available milestone: "26.4.0-alpha02" 

    const val io_arrow_kt: String =
            "0.7.3" // No update information. Is this dependency available on jcenter or mavenCentral?

    const val jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin: String =
            "0.2.5" // up-to-date

    /**
     * [junit website](http://junit.org) */
    const val junit: String = "4.12" // up-to-date

    /**
     * [kotlin-gradle-plugin website](https://kotlinlang.org/) */
    const val org_jetbrains_kotlin: String = "1.2.71" // available milestone: "1.3.0-rc-198" 

    /**
     *
     *   To update Gradle, edit the wrapper file at path:
     *      ./gradle/wrapper/gradle-wrapper.properties
     */
    object Gradle {
        const val runningVersion: String = "4.10.2"

        const val currentVersion: String = "4.10.2"

        const val nightlyVersion: String = "5.1-20181026000048+0000"

        const val releaseCandidate: String = ""
    }
}
